## Load library

In [54]:
import numpy as np

## IMPORTANT
#https://scipy.org/
## !!!!!!!!

### Basic functions

In [55]:
a = np.array([1, 2, 3], dtype = 'int32')

print(a)

[1 2 3]


In [56]:
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [57]:
## dimension (.ndim)

a.ndim

1

In [58]:
## shape (.shape)

a.shape

(3,)

In [59]:
## type (.dtype)

a.dtype

dtype('int32')

In [60]:
## size (.size)

a.size

3

In [61]:
## total size 

# a.size * a.itemsize
a.nbytes

12

### Processing data. Changing or accessing specify elements (rows, columns). Indexing

In [62]:
m = np.array ([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

print(m)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [63]:
## getting specify element from m 
m[0, 1]
### 2

m[1, 5]
### 12

12

In [64]:
## getting specify row from m 
m[0, :]
### first row

array([1, 2, 3, 4, 5, 6])

In [65]:
## getting specify column from m 

m[:, 0]
### first column

array([1, 7])

In [66]:
## gettting [startindex:endindex:stepsize]
m[0, 1 : 6 : 2]

array([2, 4, 6])

In [67]:
m[1, 5] = 20
print(a)

m[:, 2] = [1, 2]
print(a)

[1 2 3]
[1 2 3]


#### 3D 

In [68]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [69]:
## getting specify element 

b[:, 1, 1]

array([4, 8])

In [70]:
## replace 

b[:,1,:] = [[9,9], [7,7]]

print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [7 7]]]


## Initializing different types of array

In [71]:
## creating matrix of zeros 

np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [72]:
## creating matrix of ones

np.ones((2, 3), dtype = 'int32')

array([[1, 1, 1],
       [1, 1, 1]])

In [73]:
## matrix of any number

np.full((3, 3), 4.5, dtype = 'float32')

array([[4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5]], dtype=float32)

In [74]:
## matrix of (full_like)

np.full_like(m, 4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [75]:
## random decimal numbers

# np.random.rand(4, 2, 5)

np.random.random_sample(a.shape)

array([0.27541724, 0.82403085, 0.52614273])

In [76]:
## random Integer values

#np.random.randint(7)

np.random.randint(-12, 9, size = (3, 3))

array([[-10,  -7, -12],
       [  1,   5, -12],
       [  1,   7,   0]])

In [77]:
# identity matrix (one parameter)

np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [78]:
# arr = np.array([1, 2, 3])

# r1 = np.repeat(arr, 3, axis = 0)

arr = np.array([[1, 2, 3]])

r1 = np.repeat(arr, 3, axis = 0)

print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [79]:
a = np.ones((5,5))
print(a)

b = np.zeros((3,3))
b[1,1] = 9
print(b)

a[1:4, 1:4] = b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Coping arrays

In [80]:
a = np.array([1, 2, 3])

## wrong way
# b = a
# b[0] = 100
# print(a)

b = a.copy()
b[0] = 100

print(a)

[1 2 3]


## Mathematics

In [81]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [82]:
a + 2
a - 2
a * 2
a / 2
a += 2
a ** 2 #pow of

array([ 9, 16, 25, 36], dtype=int32)

In [83]:
b = np.array([1, 0, 1, 0])
a + b

array([4, 4, 6, 6])

In [84]:
## take the sin, cos
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

#### Linear Algebra

In [85]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [86]:
## finding the determinant
c = np.identity(3)
np.linalg.det(c)


1.0

## Statistics

In [89]:
stat = np.array([[1, 2, 3], [4, 5, 6]])

stat

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
np.min(stat)

1

In [95]:
np.max(stat, axis=1) (m x n, 0 = n, 1 = m)

array([3, 6])

In [97]:
np.sum(stat, axis = 0)

array([5, 7, 9])

#### Reorganizing arrays

In [105]:
before = np.array([[1, 2, 3, 8, 5], [4, 5, 6, 11, 15]])
print(before)

after = before.reshape((5,2))
print(after)

[[ 1  2  3  8  5]
 [ 4  5  6 11 15]]
[[ 1  2]
 [ 3  8]
 [ 5  4]
 [ 5  6]
 [11 15]]


#### Vertically stacking vectors

In [108]:
v1 = np.array([1, 2, 3, 5])
v2 = np.array([4, 1, 8, 8])



np.vstack([v2, v1, v1, v1])

array([[4, 1, 8, 8],
       [1, 2, 3, 5],
       [1, 2, 3, 5],
       [1, 2, 3, 5]])

#### Horizontal stacking

In [111]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

#### Loading data from file

In [117]:
data = np.genfromtxt('data.txt', delimiter = ',')
data.astype('int32')

data = data.astype('int32')
data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### Boolean mastking and advanced indexing

In [119]:
data [data > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [120]:
## It is possible to index with a list
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 4]]


array([2, 3, 5])

In [122]:
np.any(data > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [124]:
np.all(data > 50, axis = 1)

array([False, False, False])

In [126]:
(~((data > 50) & (data < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])