## Load library

In [73]:
import numpy as np

### Basic functions

In [74]:
a = np.array([1, 2, 3], dtype = 'int32')

print(a)

[1 2 3]


In [75]:
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [76]:
## dimension (.ndim)

a.ndim

1

In [77]:
## shape (.shape)

a.shape

(3,)

In [78]:
## type (.dtype)

a.dtype

dtype('int32')

In [79]:
## size (.size)

a.size

3

In [80]:
## total size 

# a.size * a.itemsize
a.nbytes

12

### Processing data. Changing or accessing specify elements (rows, columns). Indexing

In [81]:
m = np.array ([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

print(m)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [82]:
## getting specify element from m 
m[0, 1]
### 2

m[1, 5]
### 12

12

In [83]:
## getting specify row from m 
m[0, :]
### first row

array([1, 2, 3, 4, 5, 6])

In [84]:
## getting specify column from m 

m[:, 0]
### first column

array([1, 7])

In [85]:
## gettting [startindex:endindex:stepsize]
m[0, 1 : 6 : 2]

array([2, 4, 6])

In [86]:
m[1, 5] = 20
print(a)

m[:, 2] = [1, 2]
print(a)

[1 2 3]
[1 2 3]


#### 3D 

In [87]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [88]:
## getting specify element 

b[:, 1, 1]

array([4, 8])

In [89]:
## replace 

b[:,1,:] = [[9,9], [7,7]]

print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [7 7]]]


## Initializing different types of array

In [90]:
## creating matrix of zeros 

np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [91]:
## creating matrix of ones

np.ones((2, 3), dtype = 'int32')

array([[1, 1, 1],
       [1, 1, 1]])

In [92]:
## matrix of any number

np.full((3, 3), 4.5, dtype = 'float32')

array([[4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5]], dtype=float32)

In [94]:
## matrix of (full_like)

np.full_like(m, 4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [101]:
## random decimal numbers

# np.random.rand(4, 2, 5)

np.random.random_sample(a.shape)

array([0.06380502, 0.88039714, 0.59487797])

In [108]:
## random Integer values

#np.random.randint(7)

np.random.randint(-12, 9, size = (3, 3))

array([[  5,  -4,  -3],
       [-12,   2,   0],
       [  5,  -7,  -6]])

In [109]:
# identity matrix (one parameter)

np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [115]:
# arr = np.array([1, 2, 3])

# r1 = np.repeat(arr, 3, axis = 0)

arr = np.array([[1, 2, 3]])

r1 = np.repeat(arr, 3, axis = 0)

print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [130]:
a = np.ones((5,5))
print(a)

b = np.zeros((3,3))
b[1,1] = 9
print(b)

a[1:4, 1:4] = b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
